# Generated by Django 2.2 on 2021-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
